apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-node-js-deployment
  labels:
    app: next-js
spec:
  replicas: 2
  selector:
    matchLabels:
      app: next-js
  template:
    metadata:
      labels:
        app: next-js
    spec:
      containers:
      - name: next-js
        image: thethymca/next-node-js-app:"4"
        ports:
        - containerPort: 3000
