pipeline {
    agent any
    environment {
        DOCKERTAG = "${BUILD_NUMBER}"
        GIT_REPO_NAME = "docker-jenkins-argocd-using-next_js"
    }
    stages {
        stage ('Update Deployment Manifest file') {
            steps {
                script {
                    //catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                        withCredentials([usernamePassword(
                            credentialsId: 'git-credentials',
                            usernameVariable: 'GIT_USERNAME',
                            passwordVariable: 'GIT_PASSWORD'
                        )]) {
                            sh """
                                git config user.email "harkaur02@gmail.com"
                                git config user.name "harkaur02"

                                echo "deployment.yaml file before update"
                                cat deployment.yaml

                                //sed -i 's+thethymca/next-node-js-app:*+thethymca/next-node-js-app:'"$DOCKERTAG"'+g'

                                sed -i 's+thethymca/next-node-js-app:*+thethymca/next-node-js-app:'"$DOCKERTAG"'+g' deployment.yaml

                                echo "deployment.yaml file after update.....
                                cat deployment.yaml

                                git add deployment.yaml
                                git commit -m "updated image tag to current $BUILD_NUMBER"

                                git push https://$GIT_USERNAME:$GIT_PASSWORD@github.com/$GIT_USERNAME/$GIT_REPO_NAME HEAD:master
                            """
                        }
                    //}
                }
            }
        }
    }
}
